spring:
  application:
    name: social-network
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_schema: social_network

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

server:
  error:
    include-message: always

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.web: debug

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true