spring:
  application:
    name: social-network
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_schema: social_network

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

server:
  servlet:
    context-path: /api
  error:
    include-message: always

security:
  argon2:
    salt-length: 16
    hash-length: 32
    parallelism: 1
    memory: 20000
    iterations: 2

jwt:
  public:
    key: classpath:authz.pub
  private:
    key: classpath:authz.pem

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.web: debug

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true