DROP SCHEMA IF EXISTS social_network CASCADE;

CREATE SCHEMA social_network;

CREATE TABLE social_network.app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_app_user_id PRIMARY KEY (id),
    CONSTRAINT uk_app_user_username UNIQUE (username),
    CONSTRAINT uk_app_user_email UNIQUE (email)
);

CREATE TABLE social_network.person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app_user_id BIGINT NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    birth_date DATE NOT NULL,
    bio VARCHAR(500),
    avatar_url VARCHAR(512),
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_person_id PRIMARY KEY (id),
    CONSTRAINT uk_person_app_user_id UNIQUE (app_user_id),
    CONSTRAINT fk_person_app_user_id FOREIGN KEY (app_user_id) REFERENCES social_network.app_user (id) ON DELETE RESTRICT
);

CREATE TABLE social_network.social_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500),
    requires_member_approval BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_social_group_id PRIMARY KEY (id),
    CONSTRAINT fk_social_group_owner_id FOREIGN KEY (owner_id) REFERENCES social_network.person (id) ON DELETE RESTRICT
);

CREATE TABLE social_network.group_member (
    social_group_id BIGINT NOT NULL,
    person_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_group_member PRIMARY KEY (social_group_id, person_id),
    CONSTRAINT fk_group_member_social_group_id FOREIGN KEY (social_group_id) REFERENCES social_network.social_group (id) ON DELETE RESTRICT,
    CONSTRAINT fk_group_member_person_id FOREIGN KEY (person_id) REFERENCES social_network.person (id) ON DELETE RESTRICT,
    CONSTRAINT ck_group_member_role CHECK (role IN ('OWNER', 'ADMIN', 'MODERATOR', 'MEMBER')),
    CONSTRAINT ck_group_member_status CHECK (status IN ('ACTIVE', 'BANNED', 'LEFT')),
    CONSTRAINT ck_group_member_owner_status CHECK (role <> 'OWNER' OR status = 'ACTIVE')
);

CREATE UNIQUE INDEX uk_group_member_owner
ON social_network.group_member (social_group_id)
WHERE role = 'OWNER';

CREATE TABLE social_network.group_membership_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    social_group_id BIGINT NOT NULL,
    person_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    responded_at TIMESTAMPTZ,
    responded_by_person_id BIGINT,

    CONSTRAINT pk_group_membership_request_id PRIMARY KEY (id),
    CONSTRAINT fk_group_membership_request_social_group_id FOREIGN KEY (social_group_id) REFERENCES social_network.social_group (id) ON DELETE RESTRICT,
    CONSTRAINT fk_group_membership_request_person_id FOREIGN KEY (person_id) REFERENCES social_network.person (id) ON DELETE RESTRICT,
    CONSTRAINT fk_group_membership_request_responded_by_person_id FOREIGN KEY (responded_by_person_id) REFERENCES social_network.person (id) ON DELETE RESTRICT,
    CONSTRAINT ck_group_membership_request_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT ck_group_membership_request_response CHECK ((status = 'PENDING' AND responded_at IS NULL AND responded_by_person_id IS NULL) OR (status <> 'PENDING' AND responded_at IS NOT NULL AND responded_by_person_id IS NOT NULL)),
    CONSTRAINT ck_group_membership_request_not_self CHECK (person_id <> responded_by_person_id OR responded_by_person_id IS NULL)
);

CREATE TABLE social_network.post (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    person_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    social_group_id BIGINT,
    visibility VARCHAR(20) NOT NULL DEFAULT 'PUBLIC',
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_post_id PRIMARY KEY (id),
    CONSTRAINT fk_post_person_id FOREIGN KEY (person_id) REFERENCES social_network.person (id) ON DELETE RESTRICT,
    CONSTRAINT fk_post_social_group_id FOREIGN KEY (social_group_id) REFERENCES social_network.social_group (id) ON DELETE RESTRICT,
    CONSTRAINT ck_post_visibility CHECK (visibility IN ('PUBLIC', 'FRIENDS', 'PRIVATE'))
);

CREATE TABLE social_network.friend_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    requester_id BIGINT NOT NULL,
    recipient_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    responded_at TIMESTAMPTZ,

    CONSTRAINT pk_friend_request_id PRIMARY KEY (id),
    CONSTRAINT fk_friend_request_requester_id FOREIGN KEY (requester_id) REFERENCES social_network.person (id) ON DELETE RESTRICT,
    CONSTRAINT fk_friend_request_recipient_id FOREIGN KEY (recipient_id) REFERENCES social_network.person (id) ON DELETE RESTRICT,
    CONSTRAINT ck_friend_request_different_people CHECK (requester_id <> recipient_id),
    CONSTRAINT ck_friend_request_status CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT ck_friend_request_responded_at CHECK ((status = 'PENDING' AND responded_at IS NULL) OR (status <> 'PENDING' AND responded_at IS NOT NULL))
);

CREATE UNIQUE INDEX uk_friend_request_pending_pair
ON social_network.friend_request (LEAST(requester_id, recipient_id), GREATEST(requester_id, recipient_id))
WHERE status = 'PENDING';

CREATE TABLE social_network.friendship (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    person_a_id BIGINT NOT NULL,
    person_b_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_friendship_id PRIMARY KEY (id),
    CONSTRAINT fk_friendship_person_a_id FOREIGN KEY (person_a_id) REFERENCES social_network.person (id) ON DELETE RESTRICT,
    CONSTRAINT fk_friendship_person_b_id FOREIGN KEY (person_b_id) REFERENCES social_network.person (id) ON DELETE RESTRICT,
    CONSTRAINT ck_friendship_different_people CHECK (person_a_id <> person_b_id),
    CONSTRAINT ck_friendship_person_order CHECK (person_a_id < person_b_id),
    CONSTRAINT uk_friendship_person_pair UNIQUE (person_a_id, person_b_id)
);

CREATE TABLE social_network.post_reaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_id BIGINT NOT NULL,
    person_id BIGINT NOT NULL,
    reaction_type VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_post_reaction_id PRIMARY KEY (id),
    CONSTRAINT fk_post_reaction_post_id FOREIGN KEY (post_id) REFERENCES social_network.post (id) ON DELETE RESTRICT,
    CONSTRAINT fk_post_reaction_person_id FOREIGN KEY (person_id) REFERENCES social_network.person (id) ON DELETE RESTRICT,
    CONSTRAINT uk_post_reaction_post_person UNIQUE (post_id, person_id),
    CONSTRAINT ck_post_reaction_type CHECK (reaction_type IN ('LIKE', 'LOVE', 'HAHA', 'WOW', 'SAD', 'ANGRY'))
);

CREATE TABLE social_network.post_comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_id BIGINT NOT NULL,
    person_id BIGINT NOT NULL,
    parent_comment_id BIGINT,
    content TEXT NOT NULL,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_post_comment_id PRIMARY KEY (id),
    CONSTRAINT fk_post_comment_post_id FOREIGN KEY (post_id) REFERENCES social_network.post (id) ON DELETE RESTRICT,
    CONSTRAINT fk_post_comment_person_id FOREIGN KEY (person_id) REFERENCES social_network.person (id) ON DELETE RESTRICT,
    CONSTRAINT fk_post_comment_parent_id FOREIGN KEY (parent_comment_id) REFERENCES social_network.post_comment (id) ON DELETE RESTRICT
);

CREATE TABLE social_network.post_share (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_id BIGINT NOT NULL,
    person_id BIGINT NOT NULL,
    comment TEXT,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_post_share_id PRIMARY KEY (id),
    CONSTRAINT fk_post_share_post_id FOREIGN KEY (post_id) REFERENCES social_network.post (id) ON DELETE RESTRICT,
    CONSTRAINT fk_post_share_person_id FOREIGN KEY (person_id) REFERENCES social_network.person (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uk_group_membership_request_pending
ON social_network.group_membership_request (social_group_id, person_id)
WHERE status = 'PENDING';

CREATE TABLE social_network.conversation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_conversation_id PRIMARY KEY (id),
    CONSTRAINT ck_conversation_type CHECK (type IN ('DIRECT', 'GROUP'))
);

CREATE TABLE social_network.conversation_participant (
    conversation_id BIGINT NOT NULL,
    person_id BIGINT NOT NULL,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    left_at TIMESTAMPTZ,

    CONSTRAINT pk_conversation_participant PRIMARY KEY (conversation_id, person_id),
    CONSTRAINT fk_conversation_participant_conversation_id FOREIGN KEY (conversation_id) REFERENCES social_network.conversation (id) ON DELETE CASCADE,
    CONSTRAINT fk_conversation_participant_person_id FOREIGN KEY (person_id) REFERENCES social_network.person (id) ON DELETE RESTRICT,
    CONSTRAINT ck_conversation_participant_dates CHECK (left_at IS NULL OR left_at >= joined_at)
);

CREATE TABLE social_network.message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    conversation_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    edited_at TIMESTAMPTZ,

    CONSTRAINT pk_message_id PRIMARY KEY (id),
    CONSTRAINT fk_message_conversation_id FOREIGN KEY (conversation_id) REFERENCES social_network.conversation (id) ON DELETE RESTRICT,
    CONSTRAINT fk_message_sender_id FOREIGN KEY (sender_id) REFERENCES social_network.person (id) ON DELETE RESTRICT,
    CONSTRAINT ck_message_edited_at CHECK (edited_at IS NULL OR edited_at >= created_at)
);

CREATE TABLE social_network.notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    person_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    message VARCHAR(500) NOT NULL,
    reference_id BIGINT,
    read_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_notification_id PRIMARY KEY (id),
    CONSTRAINT fk_notification_person_id FOREIGN KEY (person_id) REFERENCES social_network.person (id) ON DELETE RESTRICT
);


CREATE INDEX idx_group_owner_id ON social_network.social_group (owner_id);

CREATE INDEX idx_group_member_person_id ON social_network.group_member (person_id);
CREATE INDEX idx_group_member_group_status ON social_network.group_member (social_group_id, status);
CREATE INDEX idx_group_member_person_status ON social_network.group_member (person_id, status);

CREATE INDEX idx_group_membership_request_person_status ON social_network.group_membership_request (person_id, status);
CREATE INDEX idx_group_membership_request_group_status ON social_network.group_membership_request (social_group_id, status);
CREATE INDEX idx_group_membership_request_responded_by ON social_network.group_membership_request (responded_by_person_id);

CREATE INDEX idx_post_person_id ON social_network.post (person_id);
CREATE INDEX idx_post_created_at ON social_network.post (created_at DESC);
CREATE INDEX idx_post_person_created_at ON social_network.post (person_id, created_at DESC);
CREATE INDEX idx_post_group_created_at ON social_network.post (social_group_id, created_at DESC);

CREATE INDEX idx_friend_request_recipient_status ON social_network.friend_request (recipient_id, status);
CREATE INDEX idx_friend_request_requester_status ON social_network.friend_request (requester_id, status);

CREATE INDEX idx_friendship_person_a_id ON social_network.friendship (person_a_id);
CREATE INDEX idx_friendship_person_b_id ON social_network.friendship (person_b_id);

CREATE INDEX idx_post_reaction_person_id ON social_network.post_reaction (person_id);
CREATE INDEX idx_post_reaction_post_id ON social_network.post_reaction (post_id);

CREATE INDEX idx_post_comment_post_id ON social_network.post_comment (post_id);
CREATE INDEX idx_post_comment_person_id ON social_network.post_comment (person_id);
CREATE INDEX idx_post_comment_parent_comment_id ON social_network.post_comment (parent_comment_id);

CREATE INDEX idx_conversation_participant_person_id ON social_network.conversation_participant (person_id);

CREATE INDEX idx_message_conversation_created_at ON social_network.message (conversation_id, created_at);
CREATE INDEX idx_message_sender_id ON social_network.message (sender_id);

CREATE INDEX idx_notification_person_created_at ON social_network.notification (person_id, created_at DESC);
CREATE INDEX idx_notification_person_unread ON social_network.notification (person_id, created_at DESC) WHERE read_at IS NULL;